name: Build and Package Extensions

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-zips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Package Extensions
        run: pnpm zip:all

      - name: Debug - List output directory
        run: |
          echo "=== Contents of .output directory ==="
          ls -la .output/ || echo "No .output directory found"
          echo "=== All zip files in project ==="
          find . -name "*.zip" -type f || echo "No zip files found"

          - name: Get extension zip paths
          id: zip_paths
          run: |
            find .output -name "*-chrome.zip" -type f | head -1 > chrome_path.txt
            find .output -name "*-firefox.zip" -type f | head -1 > firefox_path.txt
            CHROME_ZIP=$(cat chrome_path.txt)
            FIREFOX_ZIP=$(cat firefox_path.txt)
            echo "chrome_zip=${CHROME_ZIP}" >> "${GITHUB_OUTPUT}"
            echo "firefox_zip=${FIREFOX_ZIP}" >> "${GITHUB_OUTPUT}"
            echo "Chrome zip: ${CHROME_ZIP}"
            echo "Firefox zip: ${FIREFOX_ZIP}"
            rm chrome_path.txt firefox_path.txt

          - name: Prepare artifacts directory
          run: |
            mkdir -p artifacts
            cp "${{ steps.zip_paths.outputs.chrome_zip }}" artifacts/
            cp "${{ steps.zip_paths.outputs.firefox_zip }}" artifacts/

          - name: Upload Chrome extension artifact
            uses: actions/upload-artifact@v4
            with:
              name: chrome-extension
              path: artifacts/*-chrome.zip

          - name: Upload Firefox extension artifact
            uses: actions/upload-artifact@v4
            with:
              name: firefox-extension
              path: artifacts/*-firefox.zip

  report:
    needs: [build-zips]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Report failure
        run: |
          echo "❌ Build or packaging failed."
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
