name: Build and Package Extensions

on:
  pull_request:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: |
          pnpm install --frozen-lockfile
          pnpm zip:all

      - name: Extract package info
        id: pkg
        run: |
          NAME=$(node -p "require('./package.json').name.replace(/[@\/]/g, '-')")
          VERSION=$(node -p "require('./package.json').version")
          echo "name=${NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Verify zips exist
        run: |
          ls -la .output/
          [ -f ".output/${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}-chrome.zip" ] || exit 1
          [ -f ".output/${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}-firefox.zip" ] || exit 1

      - name: Upload Chrome (direct from .output)
        uses: actions/upload-artifact@v4
        with:
          name: '${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}-chrome-mv3'
          path: '.output/${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}-chrome.zip'

      - name: Upload Firefox (direct from .output)
        uses: actions/upload-artifact@v4
        with:
          name: '${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}-firefox-mv2'
          path: '.output/${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}-firefox.zip'
